#!/usr/bin/env bash
#A Bash script that displays the username, userid and Home directory path for the user of the content of the file /etc/passwd
while IFS=: read -r username password userid groupid userid_info home_directory command_shell ; do
	echo "The user $username is part of the $groupid gang, lives in $home_directory and rides $command_shell. $userid's place is protected by the passcode $password, more info about the user here: $userid_info"
done < /etc/passwd	
