#!/usr/bin/env bash
# Parse the Apache log and group by IP and HTTP code, then display occurrences in descending order
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
