#!/usr/bin/env bash
#Creating a while loop that displays Best School 10 time but with an if on 9th time
i=1
while [ $i -le 10 ]; do
	if [ $i -eq 9 ]; then
		echo -e "Best School \nHi"
	
	else
	      	echo "Best School"
	fi
	i=$((i+1))
done
