#!/usr/bin/env bash
#Creating a while loop that displays an if else application
i=1
while [ $i -le 10 ]; do
        if [ $i -eq 4 ]; then
                echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"

        else
                echo "Best School"
        fi
        i=$((i+1))
done
