#!/usr/bin/env bash
# Display all processes for all users, including those without a TTY, in a user-oriented format, and show the process hierarchy
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --sort=start_time --forest
